### ISSUE TITLE
Error when calling  ChessLogic.Game.from_pgn/1

### ISSUE THREAD

**Issue by abdul-playlogix** [kokolegorille/chess_logic#1]
Get the following error when invoking the function:

```iex(1)> ChessLogic.Game.from_pgn("1. a4 a5 2. h4 h5")
** (MatchError) no match of right hand side value: {:error, {1, :pgn_parser, ['syntax error before: ', ['"1."']]}}
    (chess_logic) lib/chess_logic/game.ex:195: ChessLogic.Game.from_pgn/1
```

Attempted to interpret the yecc spec for errors, but I'm not super familiar with it and couldn't spot any obvious errors.

I attempted the function on the following machines: 
1. windows machine running Elixir 1.7.1 
2. ubuntu server running Elixir 1.7.3.

Both using iex.

Any idea what why I am experiencing this issue?

**Comment by kokolegorille** [comment]
Hello, sorry for late reply...

I see code seems to be broken with new Elixir. I might have to take a look. But for what is worth... I have separated parser (and rewrote some pieces) and logic into 2 repos.

One is chess_parser, which contains the new pgn parser, and the other is chessfold. Both in my repo.

The parser works with utf8, and that might be a problem, if You import data from Windows. To convert file, I use iconv like this.

```elixir
  defp force_utf8(string) do
    if String.valid?(string) do
      string
    else
      new_string = :iconv.convert "utf-8", "ascii//translit", string
      Logger.debug fn -> "Converting #{inspect string} to #{new_string}" end
      new_string
    end
  end
```

There is a complete example of pgn processing into chess_db repo.

Please show the file You want to import.

**Comment by kokolegorille** [comment]
bump to version 0.3.0 and use utf8 file should work for now, closing the issue.
